name: Deploy to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BUCKET_NAME: ${{ secrets.GCP_PROJECT_ID }}-website

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend-static/package-lock.json

    - name: Install dependencies
      working-directory: frontend-static
      run: npm ci

    - name: Build Angular app
      working-directory: frontend-static
      run: npm run build --configuration production

    - name: Google Auth
      id: auth
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Upload to Cloud Storage
      run: |
        gsutil -m rsync -r frontend-static/dist/frontend gs://$BUCKET_NAME

    - name: Set Cache-Control metadata
      run: |
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://$BUCKET_NAME/**.css
        gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://$BUCKET_NAME/**.js
        gsutil -m setmeta -h "Cache-Control:public, max-age=86400" gs://$BUCKET_NAME/assets/**
        gsutil setmeta -h "Cache-Control:no-cache, no-store, must-revalidate" gs://$BUCKET_NAME/index.html